// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/12/2025, 15.39.36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/HP/Remote For Hive/landing-page/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/plugins/**/*.{js,ts,mjs}","C:/Users/HP/Remote For Hive/landing-page/composables/**/*.{js,ts,mjs}","C:/Users/HP/Remote For Hive/landing-page/utils/**/*.{js,ts,mjs}","C:/Users/HP/Remote For Hive/landing-page/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/Remote For Hive/landing-page/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;